project:
  type: website
  output-dir: docs

webr:
  packages: ['tidyverse', 'palmerpenguins', 'gt', 'dplyr', 'DT', 'htmltools']
number-sections: true

website:
  title: "Data Visualization Tutorials"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: histogram.qmd
        text: Histograms
      - href: boxPlot.qmd
        text: Box Plots
      - href: scatterPlot.qmd
        text: Scatter Plots
      - href: barPlot.qmd
        text: Bar Plots
      - href: tipsAndTricks.qmd
        text: Tips and Tricks
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true